CONFIG_FILE = "gimpml_config.json"
ERROR_LOG = "error_log"
ERROR_LOG_FILE = ERROR_LOG + "_{}.txt"
WEIGHTS_FOLDER  = "weights"
TMP_DIR = "gimpml"
ERROR_TEXT = "Processing was not performed due to errors."